name: NgrokCommunication
version: '${project.version}'
main: me.infinity.ngrokcom.NgrokCommunication
api-version: 1.19
folia-supported: true
load: STARTUP
libraries:
  - net.dv8tion:JDA:5.0.0-beta.18
